Water: 0
Wind:
  - 0.2
  - 1.0
Worm:
  - 0
  - 0.5
  - 0.5
  - 0
  - 2.0
  - 2.0
  - 6.0
  - 0.5
  - 4.0
  - 10
  - 1
  - 25
Small Girder:
  - 1.5
  - 0.4
Large Girder:
  - 3
  - 0.4
Bazooka:
  - 10
  - 0.25
  - 35
  - 6.0
  - 2.0
Mortar:
  - 10
  - 0.25
  - 25.0
  - 4.0
  - 2
  - 6
  - 0.5
  - 0.10
  - 5.0
GreenGrenade:
  - 10
  - 0.25
  - 0.5
  - 35.0
  - 3.0
  - 2
RedGrenade:
  - 10
  - 0.25
  - 0.5
  - 30.0
  - 2.0
  - 2.0
  - 6
  - 0.5
  - 0.10
  - 5.0
Banana:
  - 10
  - 0.25
  - 1
  - 60.0
  - 6.0
  - 2.0
HolyGrenade:
  - 10
  - 0.25
  - 0.5
  - 130.0
  - 2
  - 6.0
Dynimite:
  - 0.25
  - 0
  - 50
  - 2
  - 2.0
Bate:
  - 10
  - 10
AirAttack:
  - 1.0
  - 0.25
  - 40.0
  - 250.0
  - 4.0
  - 2.0
